name: macOS-build

on: push
  
jobs:
  macos-build:
    name: Build for macOS
    runs-on: macos-10.15
    steps:
      - name: Install requirements
        run: brew install cmake svn autoconf automake bison libtool pkg-config yasm
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build default
        run: |
          cd "$GITHUB_WORKSPACE"
          make update
          make
