name: macOS-build

on: push
  
jobs:
  macos-build:
    name: Build for macOS
    runs-on: macos-10.15
    steps:
      - name: Install requirements
        run: brew install cmake svn autoconf automake bison libtool pkg-config yasm
      - name: Prepare folders
        run: mkdir -p "$HOME/blender-git"
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          path: "$HOME/blender-git/blender"
      - name: Build default
        run: |
          cd "$HOME/blender-git/blender"
          make update
          make
